### PR TITLE
Improve meson build system

### PR DESCRIPTION
**Pull request by NathanBnm**
Hi @brain-child I made some cleanup to your project structure, especially with meson files. I also created a new folder named extra into the po folder to split translations between the main ones and the metadata ones.

Once you merged this I'll be able to add French translation as well :smile:

Let me know if you have any questions.

### CODE REVIEW

**Comment by pierrefabarius** [comment]
Thank you! I'll look into it. 
But please let the name/app-id/path as it was: ```brain-child```. Otherwise the app cannot be build as flatpak.

French translation would be great!

**Comment by NathanBnm** [comment]
@pierrefabarius the app id was sometimes `brain_child` and sometimes `brain-child`. I assume it should be `brain-child` (same as your GitHub username). So what's the correct one? I actually replaced every ` brain_child` by `brain_child`.

**Comment by pierrefabarius** [comment]
@NathanBnm I'm aware of the fact that it is mixed. The thing is, that flatpak app-id's cannot contain dashes as in the org name ```brain-child```. So I have to substitute it to ```brain_child```. Also the substitution as said does not reflect the RDNN which actually is ```com.github.brain-child.moobo```. So the mixed notation is kind of a work around.

More on that on [developer.elementary.io](https://docs.elementary.io/develop/appcenter/publishing-requirements#repository-and-app-id) and on [docs.flatpak.org](https://docs.flatpak.org/en/latest/conventions.html?#application-ids)

**Comment by NathanBnm** [comment]
I understand, I'll revert these changes

**Comment by NathanBnm** [comment]
@pierrefabarius I just reverted the changes. I could build the app successfully both with meson and flatpak.

**Comment by pierrefabarius** [comment]
Looks good, thank you very much @NathanBnm.

I have two little questions:

-  the ```de.po```-file is split in two: ```po/de.po``` and ```po/extra/de.po```. The second file seems to contain the translation for the AppCenter. What about the ```pt.po```? There's only one file.

- will all (new) ```.po```-files automatically be split in two files?

**Comment by NathanBnm** [comment]
> * the `de.po`-file is split in two: `po/de.po` and `po/extra/de.po`. The second file seems to contain the translation for the AppCenter. What about the `pt.po`? There's only one file.

I actually forgot to split the newly added Portuguese translation. I'll fix this, then you will be able to merge this PR.

> * will all (new) `.po`-files automatically be split in two files?

In order to update translations files you can use the following commands:

```bash
# To update main translations
> ninja com.github.brain_child.moobo-update-po
# To update metadata translations
> ninja extra-update-po
```

**Comment by NathanBnm** [comment]
@pierrefabarius ready for review!

**Comment by pierrefabarius** [comment]
Awesome job man! Thank you very much @NathanBnm
I will merge and close this.

**Pull request merged**
